package de.exceptionflug.protocolize.world;

import static de.exceptionflug.protocolize.api.util.ProtocolVersions.*;

public enum Sound {

	AMBIENT_CAVE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "ambient_cave"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.cave")),
	AMBIENT_UNDERWATER_ENTER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.underwater.enter")),
	AMBIENT_UNDERWATER_EXIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.underwater.exit")),
	AMBIENT_UNDERWATER_LOOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.underwater.loop")),
	AMBIENT_UNDERWATER_LOOP_ADDITIONS(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.underwater.loop.additions")),
	AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.underwater.loop.additions.rare")),
	AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ambient.underwater.loop.additions.ultra.rare")),
	BLOCK_ANVIL_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.break")),
	BLOCK_ANVIL_DESTROY(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.anvil_break"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.destroy")),
	BLOCK_ANVIL_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.fall")),
	BLOCK_ANVIL_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.hit")),
	BLOCK_ANVIL_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.anvil_land"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.land")),
	BLOCK_ANVIL_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.anvil_land"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.place")),
	BLOCK_ANVIL_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.step")),
	BLOCK_ANVIL_USE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.anvil_use"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.anvil.use")),
	BLOCK_BEACON_ACTIVATE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.beacon.activate")),
	BLOCK_BEACON_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.beacon.ambient")),
	BLOCK_BEACON_DEACTIVATE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.beacon.deactivate")),
	BLOCK_BEACON_POWER_SELECT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.beacon.power.select")),
	BLOCK_BREWING_STAND_BREW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.brup:0"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.brewing_stand.brew")),
	BLOCK_BUBBLE_COLUMN_BUBBLE_POP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.bubble.column.bubble.pop")),
	BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.bubble.column.upwards.ambient")),
	BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.bubble.column.upwards.inside")),
	BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.bubble.column.whirlpool.ambient")),
	BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.bubble.column.whirlpool.inside")),
	BLOCK_CHEST_CLOSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.chestopen"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.chest.close")),
	BLOCK_CHEST_LOCKED(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_open"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.chest.locked")),
	BLOCK_CHEST_OPEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.chestclosed"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.chest.open")),
	BLOCK_CHORUS_FLOWER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.gravel:0"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.chorus_flower.death")),
	BLOCK_CHORUS_FLOWER_GROW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.gravel:0"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.chorus_flower.grow")),
	BLOCK_COMPARATOR_CLICK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.comparator.click")),
	BLOCK_CONDUIT_ACTIVATE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.conduit.activate")),
	BLOCK_CONDUIT_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.conduit.ambient")),
	BLOCK_CONDUIT_AMBIENT_SHORT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.conduit.ambient.short")),
	BLOCK_CONDUIT_ATTACK_TARGET(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.conduit.attack.target")),
	BLOCK_CONDUIT_DEACTIVATE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.conduit.deactivate")),
	BLOCK_CORAL_BLOCK_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.coral.block.break")),
	BLOCK_CORAL_BLOCK_FALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.coral.block.fall")),
	BLOCK_CORAL_BLOCK_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.coral.block.hit")),
	BLOCK_CORAL_BLOCK_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.coral.block.place")),
	BLOCK_CORAL_BLOCK_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.coral.block.step")),
	BLOCK_DISPENSER_DISPENSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.dispenser.dispense")),
	BLOCK_DISPENSER_FAIL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.dispenser.fail")),
	BLOCK_DISPENSER_LAUNCH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.dispenser.launch")),
	BLOCK_ENCHANTMENT_TABLE_USE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.enchantment.table.use")),
	BLOCK_ENDER_CHEST_CLOSE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ender.chest.close")),
	BLOCK_ENDER_CHEST_OPEN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ender.chest.open")),
	BLOCK_END_GATEWAY_SPAWN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.explode"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.end_gateway.spawn")),
	BLOCK_END_PORTAL_FRAME_FILL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.end.portal.frame.fill")),
	BLOCK_END_PORTAL_SPAWN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.end.portal.spawn")),
	BLOCK_FENCE_GATE_CLOSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_close"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.fence_gate.close")),
	BLOCK_FENCE_GATE_OPEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_open"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.fence_gate.open")),
	BLOCK_FIRE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "fire.fire"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.fire.ambient")),
	BLOCK_FIRE_EXTINGUISH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fizz"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.fire.extinguish")),
	BLOCK_FURNACE_FIRE_CRACKLE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "fire.fire"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.furnace.fire_crackle")),
	BLOCK_GLASS_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.glass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.glass.break")),
	BLOCK_GLASS_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.glass.fall")),
	BLOCK_GLASS_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.glass.hit")),
	BLOCK_GLASS_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.glass.place")),
	BLOCK_GLASS_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.glass.step")),
	BLOCK_GRASS_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.grass.break")),
	BLOCK_GRASS_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.grass.fall")),
	BLOCK_GRASS_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.grass.hit")),
	BLOCK_GRASS_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.grass.place")),
	BLOCK_GRASS_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.grass.step")),
	BLOCK_GRAVEL_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.gravel"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.gravel.break")),
	BLOCK_GRAVEL_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.gravel"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.gravel.fall")),
	BLOCK_GRAVEL_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.gravel"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.gravel.hit")),
	BLOCK_GRAVEL_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.gravel"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.gravel.place")),
	BLOCK_GRAVEL_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.gravel"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.gravel.step")),
	BLOCK_IRON_DOOR_CLOSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_close"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.iron_door.close")),
	BLOCK_IRON_DOOR_OPEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_open"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.iron_door.open")),
	BLOCK_IRON_TRAPDOOR_CLOSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_close"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.iron_trapdoor.close")),
	BLOCK_IRON_TRAPDOOR_OPEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_open"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.iron_trapdoor.open")),
	BLOCK_LADDER_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.ladder"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ladder.break")),
	BLOCK_LADDER_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.ladder"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ladder.fall")),
	BLOCK_LADDER_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.ladder"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ladder.hit")),
	BLOCK_LADDER_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.ladder"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ladder.place")),
	BLOCK_LADDER_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.ladder"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.ladder.step")),
	BLOCK_LAVA_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.lava"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.lava.ambient")),
	BLOCK_LAVA_EXTINGUISH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fizz"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.lava.extinguish")),
	BLOCK_LAVA_POP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.lavapop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.lava.pop")),
	BLOCK_LEVER_CLICK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.lever.click")),
	BLOCK_LILY_PAD_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.lily.pad.place")),
	BLOCK_METAL_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.break")),
	BLOCK_METAL_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.fall")),
	BLOCK_METAL_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.hit")),
	BLOCK_METAL_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.place")),
	BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.pressure.plate.click.off")),
	BLOCK_METAL_PRESSURE_PLATE_CLICK_ON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.pressure.plate.click.on")),
	BLOCK_METAL_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.metal.step")),
	BLOCK_NOTE_BLOCK_BASEDRUM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.basedrum")),
	BLOCK_NOTE_BLOCK_BASS(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.bass")),
	BLOCK_NOTE_BLOCK_BELL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.bell")),
	BLOCK_NOTE_BLOCK_CHIME(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.chime")),
	BLOCK_NOTE_BLOCK_FLUTE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.flute")),
	BLOCK_NOTE_BLOCK_GUITAR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.guitar")),
	BLOCK_NOTE_BLOCK_HARP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.harp")),
	BLOCK_NOTE_BLOCK_HAT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.hat")),
	BLOCK_NOTE_BLOCK_PLING(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.pling")),
	BLOCK_NOTE_BLOCK_SNARE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.snare")),
	BLOCK_NOTE_BLOCK_XYLOPHONE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.note.block.xylophone")),
	BLOCK_PISTON_CONTRACT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "tile.piston.in"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.piston.contract")),
	BLOCK_PISTON_EXTEND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "tile.piston.out"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.piston.extend")),
	BLOCK_PORTAL_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "portal.portal"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.portal.ambient")),
	BLOCK_PORTAL_TRAVEL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "portal.travel"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.portal.travel")),
	BLOCK_PORTAL_TRIGGER(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "portal.trigger"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.portal.trigger")),
	BLOCK_PUMPKIN_CARVE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.pumpkin.carve")),
	BLOCK_REDSTONE_TORCH_BURNOUT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fizz"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.redstone_torch.burnout")),
	BLOCK_SAND_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.sand"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.sand.break")),
	BLOCK_SAND_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.sand"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.sand.fall")),
	BLOCK_SAND_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.sand"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.sand.hit")),
	BLOCK_SAND_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.sand"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.sand.place")),
	BLOCK_SAND_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.sand"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.sand.step")),
	BLOCK_SHULKER_BOX_CLOSE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.shulker.box.close")),
	BLOCK_SHULKER_BOX_OPEN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.shulker.box.open")),
	BLOCK_SLIME_BLOCK_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.slime.block.break")),
	BLOCK_SLIME_BLOCK_FALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.slime.block.fall")),
	BLOCK_SLIME_BLOCK_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.slime.block.hit")),
	BLOCK_SLIME_BLOCK_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.slime.block.place")),
	BLOCK_SLIME_BLOCK_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.slime.block.step")),
	BLOCK_SNOW_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.snow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.snow.break")),
	BLOCK_SNOW_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.snow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.snow.fall")),
	BLOCK_SNOW_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.snow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.snow.hit")),
	BLOCK_SNOW_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.snow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.snow.place")),
	BLOCK_SNOW_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.snow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.snow.step")),
	BLOCK_STONE_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.break")),
	BLOCK_STONE_BUTTON_CLICK_OFF(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone_button.click_off")),
	BLOCK_STONE_BUTTON_CLICK_ON(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone_button.click_on")),
	BLOCK_STONE_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.fall")),
	BLOCK_STONE_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.hit")),
	BLOCK_STONE_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.place")),
	BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.pressure.plate.click.off")),
	BLOCK_STONE_PRESSURE_PLATE_CLICK_ON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.pressure.plate.click.on")),
	BLOCK_STONE_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.stone"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.stone.step")),
	BLOCK_TRIPWIRE_ATTACH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.tripwire.attach")),
	BLOCK_TRIPWIRE_CLICK_OFF(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.tripwire.click_off")),
	BLOCK_TRIPWIRE_CLICK_ON(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.tripwire.click_on")),
	BLOCK_TRIPWIRE_DETACH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bowhit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.tripwire.detach")),
	BLOCK_WATER_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.water"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.water.ambient")),
	BLOCK_WET_GRASS_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wet.grass.break")),
	BLOCK_WET_GRASS_FALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wet.grass.fall")),
	BLOCK_WET_GRASS_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wet.grass.hit")),
	BLOCK_WET_GRASS_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wet.grass.place")),
	BLOCK_WET_GRASS_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wet.grass.step")),
	BLOCK_WOODEN_BUTTON_CLICK_OFF(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden.button.click.off")),
	BLOCK_WOODEN_BUTTON_CLICK_ON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden.button.click.on")),
	BLOCK_WOODEN_DOOR_CLOSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_close"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden_door.close")),
	BLOCK_WOODEN_DOOR_OPEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_open"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden_door.open")),
	BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden.pressure.plate.click.off")),
	BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden.pressure.plate.click.on")),
	BLOCK_WOODEN_TRAPDOOR_CLOSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_close"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden_trapdoor.close")),
	BLOCK_WOODEN_TRAPDOOR_OPEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.door_open"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wooden_trapdoor.open")),
	BLOCK_WOOD_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wood.break")),
	BLOCK_WOOD_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wood_fall")),
	BLOCK_WOOD_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wood.hit")),
	BLOCK_WOOD_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wood.place")),
	BLOCK_WOOD_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wood.step")),
	BLOCK_WOOL_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wool.break")),
	BLOCK_WOOL_FALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wool.fall")),
	BLOCK_WOOL_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wool.hit")),
	BLOCK_WOOL_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wool.place")),
	BLOCK_WOOL_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "block.wool.step")),
	ENCHANT_THORNS_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "enchant.thorns.hit")),
	ENTITY_ARMOR_STAND_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.armor.stand.break")),
	ENTITY_ARMOR_STAND_FALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.armor.stand.fall")),
	ENTITY_ARMOR_STAND_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.armor.stand.hit")),
	ENTITY_ARMOR_STAND_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.armor.stand.place")),
	ENTITY_ARROW_HIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bowhit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.arrow.hit")),
	ENTITY_ARROW_HIT_PLAYER(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.successful_hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.arrow.hit_player")),
	ENTITY_ARROW_SHOOT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.arrow.shoot")),
	ENTITY_BAT_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.bat.loop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.bat.ambient")),
	ENTITY_BAT_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.bat.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.bat.death")),
	ENTITY_BAT_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.bat.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.bat.hurt")),
	ENTITY_BAT_LOOP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.bat.loop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.bat.loop")),
	ENTITY_BAT_TAKEOFF(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.bat.takeoff"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.bat.takeoff")),
	ENTITY_BLAZE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.blaze.breathe"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.blaze.ambient")),
	ENTITY_BLAZE_BURN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "fire.fire"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.blaze.burn")),
	ENTITY_BLAZE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.blaze.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.blaze.death")),
	ENTITY_BLAZE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.blaze.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.blaze.hurt")),
	ENTITY_BLAZE_SHOOT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.fireball4"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.blaze.shoot")),
	ENTITY_BOAT_PADDLE_LAND(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.boat.paddle.land")),
	ENTITY_BOAT_PADDLE_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.boat.paddle.water")),
	ENTITY_CAT_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cat.meow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cat.ambient")),
	ENTITY_CAT_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cat.hitt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cat.death")),
	ENTITY_CAT_HISS(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cat.hiss"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cat.hiss")),
	ENTITY_CAT_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cat.hitt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cat.hurt")),
	ENTITY_CAT_PURR(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cat.purr"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cat.purr")),
	ENTITY_CAT_PURREOW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cat.purreow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cat.purreow")),
	ENTITY_CHICKEN_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.chicken.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.chicken.ambient")),
	ENTITY_CHICKEN_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.chicken.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.chicken.death")),
	ENTITY_CHICKEN_EGG(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.chicken.plop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.chicken.egg")),
	ENTITY_CHICKEN_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.chicken.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.chicken.hurt")),
	ENTITY_CHICKEN_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.chicken.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.chicken.step")),
	ENTITY_COD_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cod.ambient")),
	ENTITY_COD_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cod.death")),
	ENTITY_COD_FLOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cod.flop")),
	ENTITY_COD_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cod.hurt")),
	ENTITY_COW_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cow.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cow.ambient")),
	ENTITY_COW_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cow.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cow.death")),
	ENTITY_COW_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cow.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cow.hurt")),
	ENTITY_COW_MILK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cow.milk")),
	ENTITY_COW_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.cow.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.cow.step")),
	ENTITY_CREEPER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.creeper.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.creeper.death")),
	ENTITY_CREEPER_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.creeper.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.creeper.hurt")),
	ENTITY_CREEPER_PRIMED(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fuse"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.creeper.primed")),
	ENTITY_DOLPHIN_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.ambient")),
	ENTITY_DOLPHIN_AMBIENT_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.ambient.water")),
	ENTITY_DOLPHIN_ATTACK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.attack")),
	ENTITY_DOLPHIN_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.death")),
	ENTITY_DOLPHIN_EAT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.eat")),
	ENTITY_DOLPHIN_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.hurt")),
	ENTITY_DOLPHIN_JUMP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.jump")),
	ENTITY_DOLPHIN_PLAY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.play")),
	ENTITY_DOLPHIN_SPLASH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.splash")),
	ENTITY_DOLPHIN_SWIM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dolphin.swim")),
	ENTITY_DONKEY_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.donkey.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.donkey.ambient")),
	ENTITY_DONKEY_ANGRY(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.donkey.angry"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.donkey.angry")),
	ENTITY_DONKEY_CHEST(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.donkey.chest")),
	ENTITY_DONKEY_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.donkey.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.donkey.death")),
	ENTITY_DONKEY_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.donkey.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.donkey.hurt")),
	ENTITY_DRAGON_FIREBALL_EXPLODE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.dragon.fireball.explode")),
	ENTITY_DROWNED_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.ambient")),
	ENTITY_DROWNED_AMBIENT_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.ambient.water")),
	ENTITY_DROWNED_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.death")),
	ENTITY_DROWNED_DEATH_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.death.water")),
	ENTITY_DROWNED_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.hurt")),
	ENTITY_DROWNED_HURT_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.hurt.water")),
	ENTITY_DROWNED_SHOOT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.shoot")),
	ENTITY_DROWNED_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.step")),
	ENTITY_DROWNED_SWIM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.drowned.swim")),
	ENTITY_EGG_THROW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.egg.throw")),
	ENTITY_ELDER_GUARDIAN_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.elder.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.ambient")),
	ENTITY_ELDER_GUARDIAN_AMBIENT_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.elder.land.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.ambient_land")),
	ENTITY_ELDER_GUARDIAN_CURSE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.elder.curse"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.curse")),
	ENTITY_ELDER_GUARDIAN_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.elder.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.death")),
	ENTITY_ELDER_GUARDIAN_DEATH_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.land.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.death_land")),
	ENTITY_ELDER_GUARDIAN_FLOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder.guardian.flop")),
	ENTITY_ELDER_GUARDIAN_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.elder.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.hurt")),
	ENTITY_ELDER_GUARDIAN_HURT_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.land.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.elder_guardian.hurt_land")),
	ENTITY_ENDERMAN_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.enderman.ambient")),
	ENTITY_ENDERMAN_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.enderman.death")),
	ENTITY_ENDERMAN_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.enderman.hurt")),
	ENTITY_ENDERMAN_SCREAM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.enderman.scream")),
	ENTITY_ENDERMAN_STARE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.enderman.stare")),
	ENTITY_ENDERMAN_TELEPORT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.enderman.teleport")),
	ENTITY_ENDERMITE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.endermite.ambient")),
	ENTITY_ENDERMITE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.kill"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.endermite.death")),
	ENTITY_ENDERMITE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.endermite.hurt")),
	ENTITY_ENDERMITE_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.endermite.step")),
	ENTITY_ENDER_DRAGON_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.dragon.ambient")),
	ENTITY_ENDER_DRAGON_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.dragon.death")),
	ENTITY_ENDER_DRAGON_FLAP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.dragon.flap")),
	ENTITY_ENDER_DRAGON_GROWL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.dragon.growl")),
	ENTITY_ENDER_DRAGON_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.dragon.hurt")),
	ENTITY_ENDER_DRAGON_SHOOT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.dragon.shoot")),
	ENTITY_ENDER_EYE_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.eye.death")),
	ENTITY_ENDER_EYE_LAUNCH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.eye.launch")),
	ENTITY_ENDER_PEARL_THROW(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ender.pearl.throw")),
	ENTITY_EVOKER_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.ambient")),
	ENTITY_EVOKER_CAST_SPELL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.cast.spell")),
	ENTITY_EVOKER_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.death")),
	ENTITY_EVOKER_FANGS_ATTACK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.fangs.attack")),
	ENTITY_EVOKER_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.hurt")),
	ENTITY_EVOKER_PREPARE_ATTACK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.prepare.attack")),
	ENTITY_EVOKER_PREPARE_SUMMON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.prepare.summon")),
	ENTITY_EVOKER_PREPARE_WOLOLO(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.evoker.prepare.wololo")),
	ENTITY_EXPERIENCE_BOTTLE_THROW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.experience_bottle.throw")),
	ENTITY_EXPERIENCE_ORB_PICKUP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.orb"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.experience_orb.pickup")),
	ENTITY_FIREWORK_ROCKET_BLAST(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.blast")),
	ENTITY_FIREWORK_ROCKET_BLAST_FAR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.blast.far")),
	ENTITY_FIREWORK_ROCKET_LARGE_BLAST(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.large.blast")),
	ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.large.blast.far")),
	ENTITY_FIREWORK_ROCKET_LAUNCH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.launch")),
	ENTITY_FIREWORK_ROCKET_SHOOT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.shoot")),
	ENTITY_FIREWORK_ROCKET_TWINKLE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.twinkle")),
	ENTITY_FIREWORK_ROCKET_TWINKLE_FAR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.firework.rocket.twinkle.far")),
	ENTITY_FISHING_BOBBER_RETRIEVE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.fishing.bobber.retrieve")),
	ENTITY_FISHING_BOBBER_SPLASH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.fishing.bobber.splash")),
	ENTITY_FISHING_BOBBER_THROW(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.fishing.bobber.throw")),
	ENTITY_FISH_SWIM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.fish.swim")),
	ENTITY_GENERIC_BIG_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.fallbig"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.big_fall")),
	ENTITY_GENERIC_BURN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fizz"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.burn")),
	ENTITY_GENERIC_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.death")),
	ENTITY_GENERIC_DRINK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.drink"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.drink")),
	ENTITY_GENERIC_EAT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.eat"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.eat")),
	ENTITY_GENERIC_EXPLODE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.explode"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.explode")),
	ENTITY_GENERIC_EXTINGUISH_FIRE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fizz"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.extinguish_fire")),
	ENTITY_GENERIC_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.hurt")),
	ENTITY_GENERIC_SMALL_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.fallsmall"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.small_fall")),
	ENTITY_GENERIC_SPLASH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic.splash")),
	ENTITY_GENERIC_SWIM(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.swim"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.generic_swim")),
	ENTITY_GHAST_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.moan"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ghast.ambient")),
	ENTITY_GHAST_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ghast.death")),
	ENTITY_GHAST_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.scream"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ghast.hurt")),
	ENTITY_GHAST_SCREAM(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.scream"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ghast.scream")),
	ENTITY_GHAST_SHOOT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.fireball4"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ghast.shoot")),
	ENTITY_GHAST_WARN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.ghast.charge"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.ghast.warn")),
	ENTITY_GUARDIAN_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.ambient")),
	ENTITY_GUARDIAN_AMBIENT_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.land.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.ambient_land")),
	ENTITY_GUARDIAN_ATTACK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.attack.loop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.attack")),
	ENTITY_GUARDIAN_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.death")),
	ENTITY_GUARDIAN_DEATH_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.land.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.death_land")),
	ENTITY_GUARDIAN_FLOP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.flop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.flop")),
	ENTITY_GUARDIAN_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.hurt")),
	ENTITY_GUARDIAN_HURT_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.guardian.land.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.guardian.hurt_land")),
	ENTITY_HORSE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.ambient")),
	ENTITY_HORSE_ANGRY(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.angry1"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.angry")),
	ENTITY_HORSE_ARMOR(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.armor"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.armor")),
	ENTITY_HORSE_BREATHE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.breathe"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.breathe")),
	ENTITY_HORSE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.death")),
	ENTITY_HORSE_EAT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, ""), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.eat")),
	ENTITY_HORSE_GALLOP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.gallop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.gallop")),
	ENTITY_HORSE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.hurt")),
	ENTITY_HORSE_JUMP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.jump"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.jump")),
	ENTITY_HORSE_LAND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.land"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.land")),
	ENTITY_HORSE_SADDLE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.leather"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.saddle")),
	ENTITY_HORSE_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.soft"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.step")),
	ENTITY_HORSE_STEP_WOOD(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.horse.step_wood")),
	ENTITY_HOSTILE_BIG_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.fallbig"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.hostile.big_fall")),
	ENTITY_HOSTILE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.hostile.death")),
	ENTITY_HOSTILE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.hostile.hurt")),
	ENTITY_HOSTILE_SMALL_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.fallsmall"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.hostile.small_fall")),
	ENTITY_HOSTILE_SPLASH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.hostile.splash")),
	ENTITY_HOSTILE_SWIM(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.swin"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.hostile.swim")),
	ENTITY_HUSK_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.husk.ambient")),
	ENTITY_HUSK_CONVERTED_TO_ZOMBIE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.husk.converted.to.zombie")),
	ENTITY_HUSK_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.husk.death")),
	ENTITY_HUSK_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.husk.hurt")),
	ENTITY_HUSK_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.husk.step")),
	ENTITY_ILLUSIONER_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.ambient")),
	ENTITY_ILLUSIONER_CAST_SPELL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.cast.spell")),
	ENTITY_ILLUSIONER_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.death")),
	ENTITY_ILLUSIONER_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.hurt")),
	ENTITY_ILLUSIONER_MIRROR_MOVE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.mirror.move")),
	ENTITY_ILLUSIONER_PREPARE_BLINDNESS(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.prepare.blindness")),
	ENTITY_ILLUSIONER_PREPARE_MIRROR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.illusioner.prepare.mirror")),
	ENTITY_IRON_GOLEM_ATTACK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.iron.golem.attack")),
	ENTITY_IRON_GOLEM_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.iron.golem.death")),
	ENTITY_IRON_GOLEM_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.iron.golem.hurt")),
	ENTITY_IRON_GOLEM_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.iron.golem.step")),
	ENTITY_ITEM_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.break")),
	ENTITY_ITEM_FRAME_ADD_ITEM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.frame.add.item")),
	ENTITY_ITEM_FRAME_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.frame.break")),
	ENTITY_ITEM_FRAME_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.frame.place")),
	ENTITY_ITEM_FRAME_REMOVE_ITEM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.frame.remove.item")),
	ENTITY_ITEM_FRAME_ROTATE_ITEM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.frame.rotate.item")),
	ENTITY_ITEM_PICKUP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.item.pickup")),
	ENTITY_LEASH_KNOT_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.leash.knot.break")),
	ENTITY_LEASH_KNOT_PLACE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.leash.knot.place")),
	ENTITY_LIGHTNING_BOLT_IMPACT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.lightning.bolt.impact")),
	ENTITY_LIGHTNING_BOLT_THUNDER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.lightning.bolt.thunder")),
	ENTITY_LINGERING_POTION_THROW(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.lingering.potion.throw")),
	ENTITY_LLAMA_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.ambient")),
	ENTITY_LLAMA_ANGRY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.angry")),
	ENTITY_LLAMA_CHEST(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.chest")),
	ENTITY_LLAMA_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.death")),
	ENTITY_LLAMA_EAT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.eat")),
	ENTITY_LLAMA_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.hurt")),
	ENTITY_LLAMA_SPIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.spit")),
	ENTITY_LLAMA_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.step")),
	ENTITY_LLAMA_SWAG(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.llama.swag")),
	ENTITY_MAGMA_CUBE_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.death")),
	ENTITY_MAGMA_CUBE_DEATH_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.death.small")),
	ENTITY_MAGMA_CUBE_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.hurt")),
	ENTITY_MAGMA_CUBE_HURT_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.hurt.small")),
	ENTITY_MAGMA_CUBE_JUMP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.jump")),
	ENTITY_MAGMA_CUBE_SQUISH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.squish")),
	ENTITY_MAGMA_CUBE_SQUISH_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.magma.cube.squish.small")),
	ENTITY_MINECART_INSIDE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "minecart.inside"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.minecart.inside")),
	ENTITY_MINECART_RIDING(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "minecart.base"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.minecart.riding")),
	ENTITY_MOOSHROOM_SHEAR(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.sheep.shear"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.mooshroom.shear")),
	ENTITY_MULE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.donkey.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.mule.ambient")),
	ENTITY_MULE_CHEST(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.mule.chest")),
	ENTITY_MULE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.donkey.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.mule.death")),
	ENTITY_MULE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.donkey.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.mule.hurt")),
	ENTITY_PAINTING_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.wool"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.painting.break")),
	ENTITY_PAINTING_PLACE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.wool"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.painting.place")),
	ENTITY_PARROT_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.ambient")),
	ENTITY_PARROT_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.death")),
	ENTITY_PARROT_EAT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.eat")),
	ENTITY_PARROT_FLY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.fly")),
	ENTITY_PARROT_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.hurt")),
	ENTITY_PARROT_IMITATE_BLAZE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.blaze")),
	ENTITY_PARROT_IMITATE_CREEPER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.creeper")),
	ENTITY_PARROT_IMITATE_DROWNED(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.drowned")),
	ENTITY_PARROT_IMITATE_ELDER_GUARDIAN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.elder.guardian")),
	ENTITY_PARROT_IMITATE_ENDERMAN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.enderman")),
	ENTITY_PARROT_IMITATE_ENDERMITE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.endermite")),
	ENTITY_PARROT_IMITATE_ENDER_DRAGON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.ender.dragon")),
	ENTITY_PARROT_IMITATE_EVOKER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.evoker")),
	ENTITY_PARROT_IMITATE_GHAST(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.ghast")),
	ENTITY_PARROT_IMITATE_HUSK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.husk")),
	ENTITY_PARROT_IMITATE_ILLUSIONER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.illusioner")),
	ENTITY_PARROT_IMITATE_MAGMA_CUBE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.magma.cube")),
	ENTITY_PARROT_IMITATE_PHANTOM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.phantom")),
	ENTITY_PARROT_IMITATE_POLAR_BEAR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.polar.bear")),
	ENTITY_PARROT_IMITATE_SHULKER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.shulker")),
	ENTITY_PARROT_IMITATE_SILVERFISH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.silverfish")),
	ENTITY_PARROT_IMITATE_SKELETON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.skeleton")),
	ENTITY_PARROT_IMITATE_SLIME(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.slime")),
	ENTITY_PARROT_IMITATE_SPIDER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.spider")),
	ENTITY_PARROT_IMITATE_STRAY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.stray")),
	ENTITY_PARROT_IMITATE_VEX(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.vex")),
	ENTITY_PARROT_IMITATE_VINDICATOR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.vindicator")),
	ENTITY_PARROT_IMITATE_WITCH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.witch")),
	ENTITY_PARROT_IMITATE_WITHER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.wither")),
	ENTITY_PARROT_IMITATE_WITHER_SKELETON(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.wither.skeleton")),
	ENTITY_PARROT_IMITATE_WOLF(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.wolf")),
	ENTITY_PARROT_IMITATE_ZOMBIE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.zombie")),
	ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.zombie.pigman")),
	ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.imitate.zombie.villager")),
	ENTITY_PARROT_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.parrot.step")),
	ENTITY_PHANTOM_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.phantom.ambient")),
	ENTITY_PHANTOM_BITE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.phantom.bite")),
	ENTITY_PHANTOM_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.phantom.death")),
	ENTITY_PHANTOM_FLAP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.phantom.flap")),
	ENTITY_PHANTOM_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.phantom.hurt")),
	ENTITY_PHANTOM_SWOOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.phantom.swoop")),
	ENTITY_PIG_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.pig.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.pig.ambient")),
	ENTITY_PIG_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.pig.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.pig.death")),
	ENTITY_PIG_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.pig.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.pig.hurt")),
	ENTITY_PIG_SADDLE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.leather"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.pig.saddle")),
	ENTITY_PIG_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.pig.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.pig.step")),
	ENTITY_PLAYER_ATTACK_CRIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.attack.crit")),
	ENTITY_PLAYER_ATTACK_KNOCKBACK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.attack.knockback")),
	ENTITY_PLAYER_ATTACK_NODAMAGE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.attack.nodamage")),
	ENTITY_PLAYER_ATTACK_STRONG(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.attack.strong")),
	ENTITY_PLAYER_ATTACK_SWEEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.attack.sweep")),
	ENTITY_PLAYER_ATTACK_WEAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.attack.weak")),
	ENTITY_PLAYER_BIG_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.fallbig"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.big_fall")),
	ENTITY_PLAYER_BREATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.breath"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.breath")),
	ENTITY_PLAYER_BURP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.burp"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.burp")),
	ENTITY_PLAYER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.death")),
	ENTITY_PLAYER_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.hurt")),
	ENTITY_PLAYER_HURT_DROWN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.hurt.drown")),
	ENTITY_PLAYER_HURT_ON_FIRE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.hurt.on.fire")),
	ENTITY_PLAYER_LEVELUP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.levelup"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.levelup")),
	ENTITY_PLAYER_SMALL_FALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.fallsmall"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.small_fall")),
	ENTITY_PLAYER_SPLASH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.splash")),
	ENTITY_PLAYER_SPLASH_HIGH_SPEED(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.splash.high.speed")),
	ENTITY_PLAYER_SWIM(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.swim"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.player.swim")),
	ENTITY_POLAR_BEAR_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.polar.bear.ambient")),
	ENTITY_POLAR_BEAR_AMBIENT_BABY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.polar.bear.ambient.baby")),
	ENTITY_POLAR_BEAR_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.polar.bear.death")),
	ENTITY_POLAR_BEAR_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.polar.bear.hurt")),
	ENTITY_POLAR_BEAR_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.polar.bear.step")),
	ENTITY_POLAR_BEAR_WARNING(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.polar.bear.warning")),
	ENTITY_PUFFER_FISH_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.ambient")),
	ENTITY_PUFFER_FISH_BLOW_OUT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.blow.out")),
	ENTITY_PUFFER_FISH_BLOW_UP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.blow.up")),
	ENTITY_PUFFER_FISH_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.death")),
	ENTITY_PUFFER_FISH_FLOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.flop")),
	ENTITY_PUFFER_FISH_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.hurt")),
	ENTITY_PUFFER_FISH_STING(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.puffer.fish.sting")),
	ENTITY_RABBIT_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.rabbit.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.rabbit.ambient")),
	ENTITY_RABBIT_ATTACK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "damage.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.rabbit.attack")),
	ENTITY_RABBIT_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.rabbit.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.rabbit.death")),
	ENTITY_RABBIT_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.rabbit.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.rabbit.hurt")),
	ENTITY_RABBIT_JUMP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.rabbit.hop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.rabbit.jump")),
	ENTITY_SALMON_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.salmon.ambient")),
	ENTITY_SALMON_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.salmon.death")),
	ENTITY_SALMON_FLOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.salmon.flop")),
	ENTITY_SALMON_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.salmon.hurt")),
	ENTITY_SHEEP_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.sheep.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.sheep.ambient")),
	ENTITY_SHEEP_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.sheep.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.sheep.death")),
	ENTITY_SHEEP_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.sheep.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.sheep.hurt")),
	ENTITY_SHEEP_SHEAR(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.sheep.shear"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.sheep.shear")),
	ENTITY_SHEEP_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.sheep.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.sheep.step")),
	ENTITY_SHULKER_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.ambient")),
	ENTITY_SHULKER_BULLET_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.bullet.hit")),
	ENTITY_SHULKER_BULLET_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.bullet.hurt")),
	ENTITY_SHULKER_CLOSE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.close")),
	ENTITY_SHULKER_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.death")),
	ENTITY_SHULKER_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.hurt")),
	ENTITY_SHULKER_HURT_CLOSED(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.hurt_closed")),
	ENTITY_SHULKER_OPEN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.open")),
	ENTITY_SHULKER_SHOOT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.shoot")),
	ENTITY_SHULKER_TELEPORT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.shulker.teleport")),
	ENTITY_SILVERFISH_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.silverfish.ambient")),
	ENTITY_SILVERFISH_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.kill"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.silverfish.death")),
	ENTITY_SILVERFISH_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.silverfish.hurt")),
	ENTITY_SILVERFISH_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.silverfish.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.silverfish.step")),
	ENTITY_SKELETON_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.skeleton.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.ambient")),
	ENTITY_SKELETON_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.skeleton.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.death")),
	ENTITY_SKELETON_HORSE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.skeleton.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton_horse.ambient")),
	ENTITY_SKELETON_HORSE_AMBIENT_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.horse.ambient.water")),
	ENTITY_SKELETON_HORSE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.skeleton.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton_horse.death")),
	ENTITY_SKELETON_HORSE_GALLOP_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.horse.gallop.water")),
	ENTITY_SKELETON_HORSE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.skeleton.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton_horse.hurt")),
	ENTITY_SKELETON_HORSE_JUMP_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.horse.jump.water")),
	ENTITY_SKELETON_HORSE_STEP_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.horse.step.water")),
	ENTITY_SKELETON_HORSE_SWIM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.horse.swim")),
	ENTITY_SKELETON_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.skeleton.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.hurt")),
	ENTITY_SKELETON_SHOOT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.shoot")),
	ENTITY_SKELETON_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.skeleton.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.skeleton.step")),
	ENTITY_SLIME_ATTACK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.slime.attack"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.attack")),
	ENTITY_SLIME_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.slime.big"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.death")),
	ENTITY_SLIME_DEATH_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.death.small")),
	ENTITY_SLIME_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.slime.big"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.hurt")),
	ENTITY_SLIME_HURT_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.hurt.small")),
	ENTITY_SLIME_JUMP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.slime.big"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.jump")),
	ENTITY_SLIME_JUMP_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.jump.small")),
	ENTITY_SLIME_SQUISH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.slime.small"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.squish")),
	ENTITY_SLIME_SQUISH_SMALL(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.slime.squish.small")),
	ENTITY_SNOWBALL_THROW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.snowball.throw")),
	ENTITY_SNOW_GOLEM_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.snow.golem.ambient")),
	ENTITY_SNOW_GOLEM_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.snow.golem.death")),
	ENTITY_SNOW_GOLEM_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.snow.golem.hurt")),
	ENTITY_SNOW_GOLEM_SHOOT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.snow.golem.shoot")),
	ENTITY_SPIDER_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.spider.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.spider.ambient")),
	ENTITY_SPIDER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.spider.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.spider.death")),
	ENTITY_SPIDER_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.spider.say"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.spider.hurt")),
	ENTITY_SPIDER_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.spider.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.spider.step")),
	ENTITY_SPLASH_POTION_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "game.potion.smash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.splash_potion.break")),
	ENTITY_SPLASH_POTION_THROW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.splash_potion.throw")),
	ENTITY_SQUID_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, ""), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.squid.ambient")),
	ENTITY_SQUID_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, ""), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.squid.death")),
	ENTITY_SQUID_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, ""), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.squid.hurt")),
	ENTITY_SQUID_SQUIRT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.squid.squirt")),
	ENTITY_STRAY_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.stray.ambient")),
	ENTITY_STRAY_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.stray.death")),
	ENTITY_STRAY_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.stray.hurt")),
	ENTITY_STRAY_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.stray.step")),
	ENTITY_TNT_PRIMED(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.fuse"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.tnt.primed")),
	ENTITY_TROPICAL_FISH_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.tropical.fish.ambient")),
	ENTITY_TROPICAL_FISH_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.tropical.fish.death")),
	ENTITY_TROPICAL_FISH_FLOP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.tropical.fish.flop")),
	ENTITY_TROPICAL_FISH_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.tropical.fish.hurt")),
	ENTITY_TURTLE_AMBIENT_LAND(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.ambient.land")),
	ENTITY_TURTLE_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.death")),
	ENTITY_TURTLE_DEATH_BABY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.death.baby")),
	ENTITY_TURTLE_EGG_BREAK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.egg.break")),
	ENTITY_TURTLE_EGG_CRACK(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.egg.crack")),
	ENTITY_TURTLE_EGG_HATCH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.egg.hatch")),
	ENTITY_TURTLE_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.hurt")),
	ENTITY_TURTLE_HURT_BABY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.hurt.baby")),
	ENTITY_TURTLE_LAY_EGG(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.lay.egg")),
	ENTITY_TURTLE_SHAMBLE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.shamble")),
	ENTITY_TURTLE_SHAMBLE_BABY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.shamble.baby")),
	ENTITY_TURTLE_SWIM(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.turtle.swim")),
	ENTITY_VEX_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vex.ambient")),
	ENTITY_VEX_CHARGE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vex.charge")),
	ENTITY_VEX_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vex.death")),
	ENTITY_VEX_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vex.hurt")),
	ENTITY_VILLAGER_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.villager.ambient")),
	ENTITY_VILLAGER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.villager.death")),
	ENTITY_VILLAGER_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.villager.hurt")),
	ENTITY_VILLAGER_NO(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.no"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.villager.no")),
	ENTITY_VILLAGER_TRADE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.villager.trade")),
	ENTITY_VILLAGER_YES(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.yes"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.villager.yes")),
	ENTITY_VINDICATOR_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vindicator.ambient")),
	ENTITY_VINDICATOR_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vindicator.death")),
	ENTITY_VINDICATOR_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.vindicator.hurt")),
	ENTITY_WITCH_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.witch.ambient")),
	ENTITY_WITCH_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villager.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.witch.death")),
	ENTITY_WITCH_DRINK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.witch.drink")),
	ENTITY_WITCH_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.villaher.hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.witch_hurt")),
	ENTITY_WITCH_THROW(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.bow"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.witch_throw")),
	ENTITY_WITHER_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wither.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.ambient")),
	ENTITY_WITHER_BREAK_BLOCK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.woodbreak"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.break_block")),
	ENTITY_WITHER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wither.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.death")),
	ENTITY_WITHER_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wither.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.hurt")),
	ENTITY_WITHER_SHOOT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wither.shoot"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.shoot")),
	ENTITY_WITHER_SKELETON_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.skeleton.ambient")),
	ENTITY_WITHER_SKELETON_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.skeleton.death")),
	ENTITY_WITHER_SKELETON_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.skeleton.hurt")),
	ENTITY_WITHER_SKELETON_STEP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.skeleton.step")),
	ENTITY_WITHER_SPAWN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wither.spawn"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wither.spawn")),
	ENTITY_WOLF_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.bark"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.ambient")),
	ENTITY_WOLF_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.death")),
	ENTITY_WOLF_GROWL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.growl"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.growl")),
	ENTITY_WOLF_HOWL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.howl"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.howl")),
	ENTITY_WOLF_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.hurt")),
	ENTITY_WOLF_PANT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.panting"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.pant")),
	ENTITY_WOLF_SHAKE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.shake"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.shake")),
	ENTITY_WOLF_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.step")),
	ENTITY_WOLF_WHINE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.wolf.whine"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.wolf.whine")),
	ENTITY_ZOMBIE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.ambient")),
	ENTITY_ZOMBIE_ATTACK_IRON_DOOR(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.wood"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.attack.iron_door")),
	ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.attack.wooden.door")),
	ENTITY_ZOMBIE_BREAK_WOODEN_DOOR(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.break.wooden.door")),
	ENTITY_ZOMBIE_CONVERTED_TO_DROWNED(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.converted.to.drowned")),
	ENTITY_ZOMBIE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.death")),
	ENTITY_ZOMBIE_DESTROY_EGG(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.destroy.egg")),
	ENTITY_ZOMBIE_HORSE_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.zombie.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie_horse.ambient")),
	ENTITY_ZOMBIE_HORSE_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.zombie.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie_horse.death")),
	ENTITY_ZOMBIE_HORSE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "hit"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.horse_hurt")),
	ENTITY_ZOMBIE_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.hurt")),
	ENTITY_ZOMBIE_INFECT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.infect"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.infect")),
	ENTITY_ZOMBIE_PIGMAN_AMBIENT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.pigman.ambient")),
	ENTITY_ZOMBIE_PIGMAN_ANGRY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.pigman.angry")),
	ENTITY_ZOMBIE_PIGMAN_DEATH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.pigman.death")),
	ENTITY_ZOMBIE_PIGMAN_HURT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.pigman.hurt")),
	ENTITY_ZOMBIE_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.step")),
	ENTITY_ZOMBIE_VILLAGER_AMBIENT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.idle"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.villager_ambient")),
	ENTITY_ZOMBIE_VILLAGER_CONVERTED(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.unfect"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.villager_converted")),
	ENTITY_ZOMBIE_VILLAGER_CURE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.remedy"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.villager_cure")),
	ENTITY_ZOMBIE_VILLAGER_DEATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.death"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.villager_death")),
	ENTITY_ZOMBIE_VILLAGER_HURT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.hurt"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.villager_hurt")),
	ENTITY_ZOMBIE_VILLAGER_STEP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.zombie.step"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "entity.zombie.villager_step")),
	ITEM_ARMOR_EQUIP_CHAIN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip_chain")),
	ITEM_ARMOR_EQUIP_DIAMOND(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip_diamond")),
	ITEM_ARMOR_EQUIP_ELYTRA(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip.elytra")),
	ITEM_ARMOR_EQUIP_GENERIC(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip_generic")),
	ITEM_ARMOR_EQUIP_GOLD(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip_gold")),
	ITEM_ARMOR_EQUIP_IRON(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.pop"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip_iron")),
	ITEM_ARMOR_EQUIP_LEATHER(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.horse.leather"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip_leather")),
	ITEM_ARMOR_EQUIP_TURTLE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.armor.equip.turtle")),
	ITEM_AXE_STRIP(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.axe.strip")),
	ITEM_BOTTLE_EMPTY(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bottle.empty")),
	ITEM_BOTTLE_FILL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bottle.fill")),
	ITEM_BOTTLE_FILL_DRAGONBREATH(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bottle.fill_dragonbreath")),
	ITEM_BUCKET_EMPTY(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bucket.empty")),
	ITEM_BUCKET_EMPTY_FISH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bucket.empty.fish")),
	ITEM_BUCKET_EMPTY_LAVA(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bucket.empty_lava")),
	ITEM_BUCKET_FILL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bucket.fill")),
	ITEM_BUCKET_FILL_FISH(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bucket.fill.fish")),
	ITEM_BUCKET_FILL_LAVA(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "liquid.splash"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.bucket.fill_lava")),
	ITEM_CHORUS_FRUIT_TELEPORT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "mob.endermen.portal"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.chorus_fruit.teleport")),
	ITEM_ELYTRA_FLYING(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, ""), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.elytra_flying")),
	ITEM_FIRECHARGE_USE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "item.fireCharge.use"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.firecharge.use")),
	ITEM_FLINTANDSTEEL_USE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "fire.ingnite"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.flintandsteel.use")),
	ITEM_HOE_TILL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "step.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.hoe.till")),
	ITEM_SHIELD_BLOCK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, ""), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.shield.block")),
	ITEM_SHIELD_BREAK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.anvil_break"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.shield.break")),
	ITEM_SHOVEL_FLATTEN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "dig.grass"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.shovel.flatten")),
	ITEM_TOTEM_USE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.totem.use")),
	ITEM_TRIDENT_HIT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.hit")),
	ITEM_TRIDENT_HIT_GROUND(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.hit.ground")),
	ITEM_TRIDENT_RETURN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.return")),
	ITEM_TRIDENT_RIPTIDE_1(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.riptide.1")),
	ITEM_TRIDENT_RIPTIDE_2(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.riptide.2")),
	ITEM_TRIDENT_RIPTIDE_3(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.riptide.3")),
	ITEM_TRIDENT_THROW(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.throw")),
	ITEM_TRIDENT_THUNDER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "item.trident.thunder")),
	MUSIC_CREATIVE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.game.creative"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.creative")),
	MUSIC_CREDITS(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.game.end.credits"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.credits")),
	MUSIC_DISC_11(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.record_11"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.11")),
	MUSIC_DISC_13(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.record_13"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.13")),
	MUSIC_DISC_BLOCKS(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.blocks"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.blocks")),
	MUSIC_DISC_CAT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.cat"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.cat")),
	MUSIC_DISC_CHIRP(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.chrip"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.chirp")),
	MUSIC_DISC_FAR(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.far"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.far")),
	MUSIC_DISC_MALL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.mall"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.mall")),
	MUSIC_DISC_MELLOHI(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.mellohi"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.mellohi")),
	MUSIC_DISC_STAL(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.stal"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.stal")),
	MUSIC_DISC_STRAD(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.strad"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.strad")),
	MUSIC_DISC_WAIT(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.wait"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.wait")),
	MUSIC_DISC_WARD(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "records.ward"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "record.ward")),
	MUSIC_DRAGON(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.game.end.dragon"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.dragon")),
	MUSIC_END(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.game.end"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.end")),
	MUSIC_GAME(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.game"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.game")),
	MUSIC_MENU(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.menu"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.menu")),
	MUSIC_NETHER(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "music.game.nether"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.nether")),
	MUSIC_UNDER_WATER(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "music.under.water")),
	UI_BUTTON_CLICK(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "random.click"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ui.button.click")),
	UI_TOAST_CHALLENGE_COMPLETE(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ui.toast.challenge.complete")),
	UI_TOAST_IN(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ui.toast.in")),
	UI_TOAST_OUT(new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "ui.toast.out")),
	WEATHER_RAIN(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "ambient.weather.rain"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "weather.rain")),
	WEATHER_RAIN_ABOVE(new SoundMapping(MINECRAFT_1_8, MINECRAFT_1_8, "ambient.weather.rain"), new SoundMapping(MINECRAFT_1_9, MINECRAFT_1_13_2, "weather.rain.above"));


	private final SoundMapping[] mappings;

	Sound(final SoundMapping... mappings) {
		this.mappings = mappings;
	}

	public static Sound getSound(final String sound, final int protocolVersion) {
		for(final Sound s : values()) {
			final String soundName = s.getSoundName(protocolVersion);
			if(soundName != null && soundName.equals(sound))
				return s;
		}
		return null;
	}

    public String getSoundName(final int protocolVersion) {
		for(final SoundMapping mapping : mappings) {
			if(mapping.getProtocolVersionRangeStart() <= protocolVersion && mapping.getProtocolVersionRangeEnd() >= protocolVersion) {
				return mapping.getSoundName();
			}
		}
		return null;
	}

}
